// home.js
let apiKey = '';

Office.onReady((info) => {
    if (info.host === Office.HostType.Word) {
        document.getElementById('save-key').onclick = saveApiKey;
        document.getElementById('run').onclick = run;
        document.getElementById('compare').onclick = comparePolices;
    }
});

function saveApiKey() {
    apiKey = document.getElementById('api-key').value;
    if (apiKey) {
        document.getElementById('api-key-input').classList.add('hidden');
        document.getElementById('review-section').classList.remove('hidden');
        document.getElementById('compare-section').classList.remove('hidden');
        document.getElementById('result').innerHTML = "API Key saved. You can now use the review feature.";
    } else {
        document.getElementById('result').innerHTML = "Please enter a valid API Key.";
    }
}

async function run() {
    if (!apiKey) {
        document.getElementById('result').innerHTML = "Please enter your API Key first.";
        return;
    }
    try {
        await Word.run(async (context) => {
            const selection = context.document.getSelection();
            selection.load("text");
            await context.sync();
            const selectedText = selection.text;
            if (!selectedText) {
                document.getElementById('result').innerHTML = "No text selected. Please select a paragraph to review.";
                return;
            }
            const review = await reviewParagraph(selectedText);
            
            // Display the formatted review in the sidebar
            displayFormattedReview(review);
        });
    } catch (error) {
        document.getElementById('result').innerHTML = `Error: ${error.message}`;
    }
}

function displayFormattedReview(review) {
    const resultDiv = document.getElementById('result');
    resultDiv.innerHTML = ''; // Clear previous content

    const sections = review.split(/\d+\.\s/).filter(Boolean);
    
    const overviewSection = document.createElement('div');
    overviewSection.innerHTML = marked(`### Overview\n\n${sections[0].trim()}`);
    resultDiv.appendChild(overviewSection);

    if (sections.length > 1) {
        const improvementSection = document.createElement('div');
        improvementSection.innerHTML = marked(`### Areas for Improvement\n\n${sections[1].trim()}`);
        resultDiv.appendChild(improvementSection);
    }

    if (sections.length > 2) {
        const suggestionsSection = document.createElement('div');
        suggestionsSection.innerHTML = marked(`### Suggestions\n\n${sections[2].trim()}`);
        const copyButton = document.createElement('button');
        copyButton.innerText = 'Copy to Clipboard';
        copyButton.className = 'bg-blue-500 text-white p-2 rounded hover:bg-blue-600 mt-2';
        copyButton.onclick = () => {
            navigator.clipboard.writeText(sections[2].trim());
            copyButton.innerText = 'Copied!';
            setTimeout(() => copyButton.innerText = 'Copy to Clipboard', 2000);
        };
        suggestionsSection.appendChild(copyButton);
        resultDiv.appendChild(suggestionsSection);
    }

    const newParagraphSection = document.createElement('div');
    newParagraphSection.innerHTML = marked(`### Suggested New Paragraph\n\n${generateNewParagraph(sections)}`);
    resultDiv.appendChild(newParagraphSection);
}

function generateNewParagraph(sections) {
    // This is a placeholder function. In a real scenario, you'd use the LLM to generate a new paragraph.
    return "This is a placeholder for the suggested new paragraph. In a real implementation, this would be generated by the LLM based on the review and suggestions.";
}

async function reviewParagraph(text) {
    const API_CONFIG = {
        model: 'gpt-4o',
        apiVersion: '2023-12-01-preview',
        deploymentName: 'gpt4o',
        azureEndpoint: 'https://cieuk1.openai.azure.com',
    };
    const prompt = `
    Review the following paragraph from a policy document against Ofsted's SCIFF framework for Outstanding. Provide areas for improvement with explanations:
    Paragraph: "${text}"
    Please structure your response as follows:
    1. Brief overview of how the paragraph aligns with the SCIFF framework
    2. Areas for improvement (if any)
    3. Specific suggestions for enhancement
    4. Suggested new paragraph incorporating the improvements
    `;
    try {
        const response = await axios.post(
            `${API_CONFIG.azureEndpoint}/openai/deployments/${API_CONFIG.deploymentName}/chat/completions?api-version=${API_CONFIG.apiVersion}`,
            {
                messages: [{ role: "user", content: prompt }],
                temperature: 0.5,
                max_tokens: 1000
            },
            {
                headers: {
                    'Content-Type': 'application/json',
                    'api-key': apiKey
                }
            }
        );
        return response.data.choices[0].message.content;
    } catch (error) {
        console.error("Error calling OpenAI API:", error);
        return "An error occurred while reviewing the paragraph. Please check your API key and try again.";
    }
}

async function comparePolices() {
    const policy1 = document.getElementById('policy1').value;
    const policy2 = document.getElementById('policy2').value;
    if (!policy1 || !policy2) {
        document.getElementById('compare-result').innerHTML = "Please enter both policies to compare.";
        return;
    }

    const API_CONFIG = {
        model: 'gpt-4o',
        apiVersion: '2023-12-01-preview',
        deploymentName: 'gpt4o',
        azureEndpoint: 'https://cieuk1.openai.azure.com',
    };
    const prompt = `
    Compare the following two policies in the context of Ofsted's SCIFF framework:
    Policy 1: "${policy1}"
    Policy 2: "${policy2}"
    Please provide a qualitative analysis of how they differ and considerations in the eyes of Ofsted / policy.
    `;

    try {
        const response = await axios.post(
            `${API_CONFIG.azureEndpoint}/openai/deployments/${API_CONFIG.deploymentName}/chat/completions?api-version=${API_CONFIG.apiVersion}`,
            {
                messages: [{ role: "user", content: prompt }],
                temperature: 0.5,
                max_tokens: 1000
            },
            {
                headers: {
                    'Content-Type': 'application/json',
                    'api-key': apiKey
                }
            }
        );
        document.getElementById('compare-result').innerHTML = marked(response.data.choices[0].message.content);
    } catch (error) {
        console.error("Error calling OpenAI API:", error);
        document.getElementById('compare-result').innerHTML = "An error occurred while comparing the policies. Please check your API key and try again.";
    }
}
